// CodeGear C++Builder
// Copyright (c) 1995, 2007 by CodeGear
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Tmsexd2007.pas' rev: 11.00

#ifndef Tmsexd2007HPP
#define Tmsexd2007HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Advsyskeyboardhookreg.hpp>	// Pascal unit
#include <Advsyskeyboardhook.hpp>	// Pascal unit
#include <Advtouchkeyboardreg.hpp>	// Pascal unit
#include <Advtouchkeyboard.hpp>	// Pascal unit
#include <Curvycontrols.hpp>	// Pascal unit
#include <Curvycontrolsreg.hpp>	// Pascal unit
#include <Advlockappreg.hpp>	// Pascal unit
#include <Advlockapp.hpp>	// Pascal unit
#include <Advlockappdlg.hpp>	// Pascal unit
#include <Aerobuttons.hpp>	// Pascal unit
#include <Aerobuttonsreg.hpp>	// Pascal unit
#include <Aerolabel.hpp>	// Pascal unit
#include <Aerolabelreg.hpp>	// Pascal unit
#include <Aerores.hpp>	// Pascal unit
#include <Aerowizardbutton.hpp>	// Pascal unit
#include <Aerowizardbuttonreg.hpp>	// Pascal unit
#include <Calpreg.hpp>	// Pascal unit
#include <Calcomp.hpp>	// Pascal unit
#include <Calcreg.hpp>	// Pascal unit
#include <Calpanel.hpp>	// Pascal unit
#include <Exeinforeg.hpp>	// Pascal unit
#include <Ellipslabel.hpp>	// Pascal unit
#include <Ellipslblreg.hpp>	// Pascal unit
#include <Exeinfo.hpp>	// Pascal unit
#include <Fsreg.hpp>	// Pascal unit
#include <Formsize.hpp>	// Pascal unit
#include <Frmshape.hpp>	// Pascal unit
#include <Frmsreg.hpp>	// Pascal unit
#include <Hotspotimagereg.hpp>	// Pascal unit
#include <Hotspotimage.hpp>	// Pascal unit
#include <Hotspoteditorcomp.hpp>	// Pascal unit
#include <Hotspoteditor.hpp>	// Pascal unit
#include <Lfreg.hpp>	// Pascal unit
#include <Linelibrary.hpp>	// Pascal unit
#include <Macrorecorder.hpp>	// Pascal unit
#include <Macrorecorderreg.hpp>	// Pascal unit
#include <Layeredform.hpp>	// Pascal unit
#include <Sysmreg.hpp>	// Pascal unit
#include <Sysmon.hpp>	// Pascal unit
#include <Moneycal.hpp>	// Pascal unit
#include <Advfocushelper.hpp>	// Pascal unit
#include <Advfocushelperreg.hpp>	// Pascal unit
#include <Advsmoothbutton.hpp>	// Pascal unit
#include <Advsmoothbuttonreg.hpp>	// Pascal unit
#include <Advsmoothcalendar.hpp>	// Pascal unit
#include <Advsmoothcalendarreg.hpp>	// Pascal unit
#include <Advsmoothdatepicker.hpp>	// Pascal unit
#include <Advsmoothdatepickerreg.hpp>	// Pascal unit
#include <Advsmoothlabel.hpp>	// Pascal unit
#include <Advsmoothlabelreg.hpp>	// Pascal unit
#include <Dbadvsmoothlabel.hpp>	// Pascal unit
#include <Dbadvsmoothlabelreg.hpp>	// Pascal unit
#include <Advsmoothlistbox.hpp>	// Pascal unit
#include <Advsmoothlistboxdragdrop.hpp>	// Pascal unit
#include <Advsmoothlistboxreg.hpp>	// Pascal unit
#include <Advsmoothcombobox.hpp>	// Pascal unit
#include <Advsmoothcomboboxreg.hpp>	// Pascal unit
#include <Advsmoothimagelistbox.hpp>	// Pascal unit
#include <Advsmoothimagelistboxreg.hpp>	// Pascal unit
#include <Advsmoothimagelistboxpicker.hpp>	// Pascal unit
#include <Advsmoothimagelistboxpickerreg.hpp>	// Pascal unit
#include <Advsmoothpanel.hpp>	// Pascal unit
#include <Advsmoothpanelreg.hpp>	// Pascal unit
#include <Advsmoothmenu.hpp>	// Pascal unit
#include <Advsmoothmenureg.hpp>	// Pascal unit
#include <Advsmoothstyles.hpp>	// Pascal unit
#include <Advsmoothfilleditor.hpp>	// Pascal unit
#include <Advsmoothhtmleditor.hpp>	// Pascal unit
#include <Advsmoothfillpreview.hpp>	// Pascal unit
#include <Advsmoothfillpreviewreg.hpp>	// Pascal unit
#include <Advsmoothselectors.hpp>	// Pascal unit
#include <Advsmoothselectorsreg.hpp>	// Pascal unit
#include <Advsmoothspin.hpp>	// Pascal unit
#include <Advsmoothspinreg.hpp>	// Pascal unit
#include <Advsmoothxpvs.hpp>	// Pascal unit
#include <Advsmootheddd.hpp>	// Pascal unit
#include <Advsmoothedit.hpp>	// Pascal unit
#include <Advsmooththeme.hpp>	// Pascal unit
#include <Advsmootheditbutton.hpp>	// Pascal unit
#include <Advsmoothspinner.hpp>	// Pascal unit
#include <Advsmoothspinnerreg.hpp>	// Pascal unit
#include <Advsmoothjogwheel.hpp>	// Pascal unit
#include <Advsmoothjogwheelreg.hpp>	// Pascal unit
#include <Advsmoothgauge.hpp>	// Pascal unit
#include <Advsmoothgaugereg.hpp>	// Pascal unit
#include <Advsmoothtrackbar.hpp>	// Pascal unit
#include <Advsmoothtrackbarreg.hpp>	// Pascal unit
#include <Advsmoothstatusindicator.hpp>	// Pascal unit
#include <Advsmoothstatusindicatorreg.hpp>	// Pascal unit
#include <Advsmoothprogressbar.hpp>	// Pascal unit
#include <Advsmoothprogressbarreg.hpp>	// Pascal unit
#include <Advsmoothtabpager.hpp>	// Pascal unit
#include <Advsmoothtabpagerreg.hpp>	// Pascal unit
#include <Advsmoothtogglebutton.hpp>	// Pascal unit
#include <Advsmoothtogglebuttonreg.hpp>	// Pascal unit
#include <Advsmoothledlabel.hpp>	// Pascal unit
#include <Advsmoothledlabelreg.hpp>	// Pascal unit
#include <Dbadvsmoothledlabel.hpp>	// Pascal unit
#include <Dbadvsmoothledlabelreg.hpp>	// Pascal unit
#include <Advsmoothdock.hpp>	// Pascal unit
#include <Advsmoothdockreg.hpp>	// Pascal unit
#include <Advsmoothdockdragdrop.hpp>	// Pascal unit
#include <Advsmoothexpanderpanel.hpp>	// Pascal unit
#include <Advsmoothexpanderpanelreg.hpp>	// Pascal unit
#include <Advsmoothexpanderbuttonpanel.hpp>	// Pascal unit
#include <Advsmoothexpanderbuttonpanelreg.hpp>	// Pascal unit
#include <Advsmoothexpandergroup.hpp>	// Pascal unit
#include <Advsmoothexpandergroupreg.hpp>	// Pascal unit
#include <Advsmoothtimeline.hpp>	// Pascal unit
#include <Advsmoothtimelinereg.hpp>	// Pascal unit
#include <Advsmoothmessagedialog.hpp>	// Pascal unit
#include <Advsmoothmessagedialogreg.hpp>	// Pascal unit
#include <Advsmoothsplashscreen.hpp>	// Pascal unit
#include <Advsmoothsplashscreenreg.hpp>	// Pascal unit
#include <Advsmoothscrollbar.hpp>	// Pascal unit
#include <Advsmoothscrollbarreg.hpp>	// Pascal unit
#include <Advsmoothslider.hpp>	// Pascal unit
#include <Advsmoothsliderreg.hpp>	// Pascal unit
#include <Advexplorertreeview.hpp>	// Pascal unit
#include <Advexplorertreeviewreg.hpp>	// Pascal unit
#include <Advsmoothmegamenu.hpp>	// Pascal unit
#include <Advsmoothmegamenureg.hpp>	// Pascal unit
#include <Advsmoothtouchkeyboard.hpp>	// Pascal unit
#include <Advsmoothtouchkeyboardreg.hpp>	// Pascal unit
#include <Advsmoothdropdownlist.hpp>	// Pascal unit
#include <Advsmoothcalculator.hpp>	// Pascal unit
#include <Advsmoothcalculatordropdown.hpp>	// Pascal unit
#include <Advsmoothcalculatorreg.hpp>	// Pascal unit
#include <Advgdipicture.hpp>	// Pascal unit
#include <Advgdipicreg.hpp>	// Pascal unit
#include <Gdippicturecontainer.hpp>	// Pascal unit
#include <Gdippicturecontainerreg.hpp>	// Pascal unit
#include <Gdipfill.hpp>	// Pascal unit
#include <Gdipmenu.hpp>	// Pascal unit
#include <Advreflectionimage.hpp>	// Pascal unit
#include <Advreflectionimagereg.hpp>	// Pascal unit
#include <Advreflectionlabel.hpp>	// Pascal unit
#include <Advreflabelreg.hpp>	// Pascal unit
#include <Advglassbutton.hpp>	// Pascal unit
#include <Advglassbuttonreg.hpp>	// Pascal unit
#include <Dbadvsmoothcombobox.hpp>	// Pascal unit
#include <Dbadvsmoothcomboboxreg.hpp>	// Pascal unit
#include <Dbadvsmoothimagelistbox.hpp>	// Pascal unit
#include <Dbadvsmoothimagelistboxreg.hpp>	// Pascal unit
#include <Dbadvsmoothlistbox.hpp>	// Pascal unit
#include <Dbadvsmoothlistboxreg.hpp>	// Pascal unit
#include <Dbadvsmoothtimeline.hpp>	// Pascal unit
#include <Dbadvsmoothtimelinereg.hpp>	// Pascal unit
#include <Dbadvsmoothdatepicker.hpp>	// Pascal unit
#include <Dbadvsmoothdatepickerreg.hpp>	// Pascal unit
#include <Advsmoothimagelistboxdragdrop.hpp>	// Pascal unit
#include <Dbadvgdippicturereg.hpp>	// Pascal unit
#include <Dbadvgdippicture.hpp>	// Pascal unit
#include <Advhorizontalpolylist.hpp>	// Pascal unit
#include <Advhorizontalpolylistreg.hpp>	// Pascal unit
#include <Advpolybox.hpp>	// Pascal unit
#include <Advpolyboxreg.hpp>	// Pascal unit
#include <Advpolylist.hpp>	// Pascal unit
#include <Advpolylistreg.hpp>	// Pascal unit
#include <Advpolypager.hpp>	// Pascal unit
#include <Advpolypagerreg.hpp>	// Pascal unit
#include <Advverticalpolylist.hpp>	// Pascal unit
#include <Advverticalpolylistreg.hpp>	// Pascal unit
#include <Customitemscontainer.hpp>	// Pascal unit
#include <Gdipbase.hpp>	// Pascal unit
#include <Gdipbuttonitem.hpp>	// Pascal unit
#include <Gdipcheckitem.hpp>	// Pascal unit
#include <Gdipcustomitem.hpp>	// Pascal unit
#include <Gdipdropdownitem.hpp>	// Pascal unit
#include <Gdipexpandableimagesectionitem.hpp>	// Pascal unit
#include <Gdipgraphicitem.hpp>	// Pascal unit
#include <Gdipgroupitem.hpp>	// Pascal unit
#include <Gdiphtmlitem.hpp>	// Pascal unit
#include <Gdiphtmlsectionitem.hpp>	// Pascal unit
#include <Gdipimageitem.hpp>	// Pascal unit
#include <Gdipimagesectionitem.hpp>	// Pascal unit
#include <Gdipimagetextbuttonitem.hpp>	// Pascal unit
#include <Gdipimagetextbuttonsectionitem.hpp>	// Pascal unit
#include <Gdipimagetextitem.hpp>	// Pascal unit
#include <Gdiplargebuttoneditem.hpp>	// Pascal unit
#include <Gdipradioitem.hpp>	// Pascal unit
#include <Gdipsectionitem.hpp>	// Pascal unit
#include <Gdiptextitem.hpp>	// Pascal unit
#include <Gdipwedgeitem.hpp>	// Pascal unit
#include <Gdipbuttonbaritem.hpp>	// Pascal unit
#include <Gdipfulldropdownitem.hpp>	// Pascal unit
#include <Gdipheaderitem.hpp>	// Pascal unit
#include <Gdiplargebuttonedhtmlitem.hpp>	// Pascal unit
#include <Gdipsplitteritem.hpp>	// Pascal unit
#include <Advsmoothslideshow.hpp>	// Pascal unit
#include <Advsmoothslideshowreg.hpp>	// Pascal unit
#include <Gdipprogressitem.hpp>	// Pascal unit
#include <Advsmoothcapacitybar.hpp>	// Pascal unit
#include <Advsmoothcapacitybarreg.hpp>	// Pascal unit
#include <Spbepc.hpp>	// Pascal unit
#include <Spbepcreg.hpp>	// Pascal unit
#include <Advsmoothpopup.hpp>	// Pascal unit
#include <Advsmoothpopupreg.hpp>	// Pascal unit
#include <Advsmoothstepcontrol.hpp>	// Pascal unit
#include <Advsmoothstepcontrolreg.hpp>	// Pascal unit
#include <Tmsw7reg.hpp>	// Pascal unit
#include <W7bars.hpp>	// Pascal unit
#include <W7buttons.hpp>	// Pascal unit
#include <W7classes.hpp>	// Pascal unit
#include <W7common.hpp>	// Pascal unit
#include <W7graphics.hpp>	// Pascal unit
#include <W7images.hpp>	// Pascal unit
#include <W7labels.hpp>	// Pascal unit
#include <W7listviewitems.hpp>	// Pascal unit
#include <W7navibuttons.hpp>	// Pascal unit
#include <W7panels.hpp>	// Pascal unit
#include <W7progressbars.hpp>	// Pascal unit
#include <Advsmoothtilelist.hpp>	// Pascal unit
#include <Advsmoothtilelistex.hpp>	// Pascal unit
#include <Advsmoothtilelisthtmlvisualizer.hpp>	// Pascal unit
#include <Advsmoothtilelistimagevisualizer.hpp>	// Pascal unit
#include <Advsmoothtilelistreg.hpp>	// Pascal unit
#include <Advmetrobutton.hpp>	// Pascal unit
#include <Advmetrobuttonreg.hpp>	// Pascal unit
#include <Advmetrodlgs.hpp>	// Pascal unit
#include <Advmetrohint.hpp>	// Pascal unit
#include <Advmetrohintreg.hpp>	// Pascal unit
#include <Advmetroprogressbar.hpp>	// Pascal unit
#include <Advmetroprogressbarreg.hpp>	// Pascal unit
#include <Advmetrores.hpp>	// Pascal unit
#include <Advmetroscrollbox.hpp>	// Pascal unit
#include <Advmetroscrollboxreg.hpp>	// Pascal unit
#include <Advmetrotaskdialog.hpp>	// Pascal unit
#include <Advmetrotaskdialogreg.hpp>	// Pascal unit
#include <Advmetrotile.hpp>	// Pascal unit
#include <Advsmoothpageslider.hpp>	// Pascal unit
#include <Advsmoothpagesliderreg.hpp>	// Pascal unit
#include <Advmetrofinddialog.hpp>	// Pascal unit
#include <Advmetroreplacedialog.hpp>	// Pascal unit
#include <Advmetroreplacedialogreg.hpp>	// Pascal unit
#include <Advmetrofinddialogreg.hpp>	// Pascal unit
#include <Advmetroform.hpp>	// Pascal unit
#include <Advsmoothcalendargroup.hpp>	// Pascal unit
#include <Advsmoothcalendargroupreg.hpp>	// Pascal unit
#include <Advdatalabel.hpp>	// Pascal unit
#include <Advdatalabelreg.hpp>	// Pascal unit
#include <Advlisteditor.hpp>	// Pascal unit
#include <Advlisteditorreg.hpp>	// Pascal unit
#include <Variants.hpp>	// Pascal unit
#include <Windows.hpp>	// Pascal unit
#include <Sysutils.hpp>	// Pascal unit
#include <Varutils.hpp>	// Pascal unit
#include <Typinfo.hpp>	// Pascal unit
#include <Classes.hpp>	// Pascal unit
#include <Inifiles.hpp>	// Pascal unit
#include <Registry.hpp>	// Pascal unit
#include <Graphics.hpp>	// Pascal unit
#include <Uxtheme.hpp>	// Pascal unit
#include <Multimon.hpp>	// Pascal unit
#include <Actnlist.hpp>	// Pascal unit
#include <Dwmapi.hpp>	// Pascal unit
#include <Controls.hpp>	// Pascal unit
#include <Themes.hpp>	// Pascal unit
#include <Menus.hpp>	// Pascal unit
#include <Helpintfs.hpp>	// Pascal unit
#include <Printers.hpp>	// Pascal unit
#include <Flatsb.hpp>	// Pascal unit
#include <Graphutil.hpp>	// Pascal unit
#include <Extctrls.hpp>	// Pascal unit
#include <Dialogs.hpp>	// Pascal unit
#include <Clipbrd.hpp>	// Pascal unit
#include <Forms.hpp>	// Pascal unit
#include <Comobj.hpp>	// Pascal unit
#include <Advgdip.hpp>	// Pascal unit
#include <Buttons.hpp>	// Pascal unit
#include <Advdwm.hpp>	// Pascal unit
#include <Advtbxpvs.hpp>	// Pascal unit
#include <Extdlgs.hpp>	// Pascal unit
#include <Mapi.hpp>	// Pascal unit
#include <Extactns.hpp>	// Pascal unit
#include <Comctrls.hpp>	// Pascal unit
#include <Jpeg.hpp>	// Pascal unit
#include <Appevnts.hpp>	// Pascal unit
#include <Advstyleif.hpp>	// Pascal unit
#include <Advxpvs.hpp>	// Pascal unit
#include <Sqltimst.hpp>	// Pascal unit
#include <Fmtbcd.hpp>	// Pascal unit
#include <Widestrings.hpp>	// Pascal unit
#include <Db.hpp>	// Pascal unit
#include <Dblogdlg.hpp>	// Pascal unit
#include <Dbpwdlg.hpp>	// Pascal unit
#include <Dbctrls.hpp>	// Pascal unit
#include <Axctrls.hpp>	// Pascal unit
#include <Olectnrs.hpp>	// Pascal unit
#include <Actnmenus.hpp>	// Pascal unit
#include <Actnman.hpp>	// Pascal unit
#include <Adveddd.hpp>	// Pascal unit
#include <Advedit.hpp>	// Pascal unit
#include <Advreplacedialogform.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Tmsexd2007
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------

}	/* namespace Tmsexd2007 */
using namespace Tmsexd2007;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Tmsexd2007
